/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passwordmanager;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author garre
 */
public class Login extends Screen {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        CenterScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_MainPassword = new javax.swing.JLabel();
        jPasswordField_MainPassword = new javax.swing.JPasswordField();
        jButton_Login = new javax.swing.JButton();
        jLabel_MainHeading = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_ForgotPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jLabel_MainPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_MainPassword.setText("Password");

        jPasswordField_MainPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_MainPasswordKeyPressed(evt);
            }
        });

        jButton_Login.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Login.setText("Login");
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });

        jLabel_MainHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_MainHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_MainHeading.setText("Welcome to Java Password Manager");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Please enter your main password to login");

        jLabel_ForgotPass.setText("Forgot password?");
        jLabel_ForgotPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ForgotPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ForgotPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_ForgotPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ForgotPassMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_MainPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField_MainPassword)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_MainHeading)
                            .addComponent(jLabel_ForgotPass))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel_MainHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_MainPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_MainPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ForgotPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Login)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_LoginActionPerformed

    // Mouse hover over 'Forgot password?'
    private void jLabel_ForgotPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ForgotPassMouseEntered
        // Change the text colour to blue
        jLabel_ForgotPass.setForeground(Color.blue);
    }//GEN-LAST:event_jLabel_ForgotPassMouseEntered

    // Mouse hover exit 'Forgot password?'
    private void jLabel_ForgotPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ForgotPassMouseExited
        // Change the text colour to black
        jLabel_ForgotPass.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_ForgotPassMouseExited

    // Forgot password text is clicked
    private void jLabel_ForgotPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ForgotPassMouseClicked
        // Inform user that all the saved passwords will be removed
        int reset = JOptionPane.showConfirmDialog(this, "Resetting the main password will also clear all saved passwords.\nAre you sure you want to reset the main password?", "Reset Password?", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);

        // If the user selects OK
        if (reset == JOptionPane.OK_OPTION) {
            // Clear the file
            try (PrintWriter pwFile = new PrintWriter(new File(PasswordManager.passwordPath))) {
                pwFile.write("");
            } catch (FileNotFoundException ex) {
                // If the file doesn't exist
                try {
                    // Create the file
                    File passwordFile = new File(PasswordManager.passwordPath);
                    passwordFile.createNewFile();
                } catch (IOException e) {
                    // Output any IO errors that occur
                    System.out.println("An error occured: " + e);
                }
            }
            // Confirmation that the passwords were cleared
            JOptionPane.showMessageDialog(this, "All passwords were cleared", "Password Reset", JOptionPane.INFORMATION_MESSAGE);
            // Hide this screen
            this.setVisible(false);
            // Display the screen to create a main password
            new SetMainPassword().setVisible(true);
        }
    }//GEN-LAST:event_jLabel_ForgotPassMouseClicked

    private void jPasswordField_MainPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_MainPasswordKeyPressed
        // If the 'ENTER' key is pressed
        if (evt.getKeyCode() == 10) {

        }
    }//GEN-LAST:event_jPasswordField_MainPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_ForgotPass;
    private javax.swing.JLabel jLabel_MainHeading;
    private javax.swing.JLabel jLabel_MainPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_MainPassword;
    // End of variables declaration//GEN-END:variables
}
